pipeline {
    agent {
        kubernetes {
           yamlFile '../jenkins/pod-template.yaml'
        }
    }
    environment {
        CI = 'true'
        IMAGE_TAG = "${BUILD_NUMBER}" // Use build number as image tag
        PIPELINE_NAME = "${env.JOB_NAME}" // send email with pipeline name
        REPO_URL = 'https://github.com/Thanh8804/hospital-booking-project.git'
        IMAGE_NAME = 'thanh8804/hospital-booking-frontend-image'
        PROJECT_NAME = 'hospital-booking-frontend'
        NOTIFY_EMAIL = 'chithanh080804@gmail.com'
        MANIFEST_REPO = 'https://github.com/Thanh8804/hospital-booking-manifests.git'
        ARGOCD_SERVER_URL = 'argocd-server.argocd.svc.cluster.local:443'
        ARGOCD_DEV_APP = 'hospital-booking-frontend-development'
        ARGOCD_PROD_APP = 'hospital-booking-frontend-production'
        SKIP_TRIVY_FAIL = 'true'
    }
    stages {
        stage('Checkout') {
            steps {
                container('node') {
                    checkout scmGit(
                        branches: [[name: '*/main']],
                        userRemoteConfigs: [[
                            url: "$REPO_URL",
                            credentialsId: 'github-token'
                        ]]
                    )
                }
            }
        }
        stage('Prepare') {
            when {
                changeset "**/frontend/**"
            }
            steps {
                container('node') {
                    sh '''
                        apk add --no-cache git openjdk17
                        npm version
                        java -version
                        export JAVA_HOME=/usr/lib/jvm/java-17-openjdk
                        export PATH=$JAVA_HOME/bin:$PATH
                   '''
                }
            }
        }
        stage('Build and Test') {
            when {
                changeset "**/frontend/**"
            }
            parallel {
                stage('Build') {
                    steps {
                        container('node') {
                            dir('frontend') {
                                sh 'npm ci'
                            }
                        }
                    }
                }
                stage('Test') {
                    steps {
                        container('node') {
                            dir('frontend') {
                                sh 'npm test -- --coverage || true' 
                            }
                        }
                    }
                }
            }
        }
        stage('Code Analysis') {
            when {
                changeset "**/frontend/**"
            }
            parallel {
                stage('SonarQube Scan') {
                    environment {
                        SONAR_AUTH_TOKEN = credentials('sonarqube-token');
                        SCANNER_HOME = tool 'sonarqube';   
                    }
                    steps {
                        container('node') {
                            dir('frontend'){
                                withSonarQubeEnv(installationName: 'sonarqube') {
                                    sh '''
                                        $SCANNER_HOME/bin/sonar-scanner \
                                        -Dsonar.projectKey=$PROJECT_NAME  \
                                        -Dsonar.host.url=$SONAR_HOST_URL \
                                        -Dsonar.login=$SONAR_AUTH_TOKEN
                                    '''
                                }
                            }
                        }
                    }
                }
                stage('Trivy Source Scan') {
                    steps {
                        container('trivy') {
                            dir('frontend') {
                                sh '''
                                    trivy fs --no-progress --severity MEDIUM,HIGH,CRITICAL \
                                    --scanners vuln,secret \
                                    --format table . > trivy-source.txt 2>&1
                                    cat trivy-source.txt
                                '''
                                sh '''
                                    CRITICAL_COUNT=$(grep 'CRITICAL:' trivy-source.txt | head -1 | awk '{print $2}')
                                    if [ "$CRITICAL_COUNT" != "" ] && [ "$CRITICAL_COUNT" -gt 0 ]; then
                                        echo "❌ Critical vulnerabilities found in source scan ($CRITICAL_COUNT)"
                                        if [ "$SKIP_TRIVY_FAIL" = "true" ]; then
                                            echo "⚠️ Skipping failure due to SKIP_TRIVY_FAIL=true"
                                        else
                                            echo "❌ Failing pipeline"
                                            exit 1
                                        fi
                                    else
                                        echo "✅ No critical vulnerabilities found."
                                    fi
                                '''
                            }
                        }
                    }
                }
            }
        }
        stage('Quality Gate') {
            when {
                changeset "**/frontend/**"
            }
            steps {
                container('node') {
                    dir('frontend'){
                        timeout(activity: true, time: 2, unit: 'MINUTES') {
                            waitForQualityGate abortPipeline: false, credentialsId: 'sonarqube-token'
                        }
                    }
                }
            }
        }
        stage('Build and Push Docker Image') {
            when {
                changeset "**/frontend/**"
            }
            steps {
                container(name: 'kaniko', shell: '/busybox/sh') {
                    dir('frontend'){
                        sh '''#!/busybox/sh
                            /kaniko/executor \
                              --context `pwd` \
                              --destination $IMAGE_NAME:$IMAGE_TAG \
                              --cache=true
                        '''
                    }
                }
            }
        }
        stage('Trivy Image Scan'){
            when {
                changeset "**/frontend/**"
            }
            steps {
              container('trivy'){
                  dir('frontend'){
                        sh '''
                        trivy image --no-progress --severity MEDIUM,HIGH,CRITICAL \
                                    --skip-files ".npm/_cacache/*" \
                                    --timeout 10m $IMAGE_NAME:$IMAGE_TAG  > trivy-image.txt 2>&1
                        cat trivy-image.txt
                        '''
                        sh '''
                        CRITICAL_COUNT=$(grep 'CRITICAL:' trivy-image.txt | head -1 | awk '{print $2}')
                        if [ "$CRITICAL_COUNT" != "" ] && [ "$CRITICAL_COUNT" -gt 0 ]; then
                            echo "❌ Critical vulnerabilities found in source scan ($CRITICAL_COUNT)"
                            if [ "$SKIP_TRIVY_FAIL" = "true" ]; then
                                echo "⚠️ Skipping failure due to SKIP_TRIVY_FAIL=true"
                            else
                                echo "❌ Failing pipeline"
                                exit 1
                            fi
                        else
                            echo "✅ No critical vulnerabilities found."
                        fi
                        '''
                    }
                }
             }
        }
        stage('Update Dev Manifests') {
            when {
                changeset "**/frontend/**"
            }
            steps {
                container('node') {
                    withCredentials([string(credentialsId: 'githubtoken', variable: 'GIT_TOKEN')]) {
                        retry(3){
                            sh '''
                                git clone $MANIFEST_REPO
                                cd hospital-booking-manifests/k8s-manifests/frontend
                                sed -i "s/newTag:.*/newTag: \\"${BUILD_NUMBER}\\"/g" overlays/dev/kustomization.yaml
                                git config user.email "$NOTIFY_EMAIL"
                                git config user.name "Thanh8804@"
                                git add overlays/dev/kustomization.yaml
                                git commit -m "Update dev image to thanh8804/hospital-booking-frontend-image:${BUILD_NUMBER}" || echo "No changes to commit"
                                git push https://$GIT_TOKEN@github.com/Thanh8804/hospital-booking-manifests.git HEAD:main
                            '''
                        }
                    }
                }
            }
        }
        stage('Trigger ArgoCD Sync DEV') {
            when {
                changeset "**/frontend/**"
            }
            steps {
                container('node') {
                    withCredentials([string(credentialsId: 'argocd-token', variable: 'ARGOCD_TOKEN')]) {
                        sh '''
                            apk add --no-cache curl
                            curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
                            install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
                            rm argocd-linux-amd64
                            argocd login $ARGOCD_SERVER_URL --username admin --password $ARGOCD_TOKEN --insecure
                            argocd app sync $ARGOCD_DEV_APP
                         '''
                     }
                 }
             }
        }
        stage('Update Prod Manifest') {
            when {
                changeset "**/frontend/**"
            }
            steps {
                container('node') {
                    withCredentials([string(credentialsId: 'githubtoken', variable: 'GIT_TOKEN')]) {
                        retry(3){
                            sh '''
                                cd hospital-booking-manifests/k8s-manifests/frontend
                                sed -i "s/newTag:.*/newTag: \\"${BUILD_NUMBER}\\"/g" overlays/prod/kustomization.yaml
                                git config user.email "$NOTIFY_EMAIL"
                                git config user.name "Thanh8804@"
                                git add overlays/prod/kustomization.yaml
                                git commit -m "Update prod image to $IMAGE_NAME:${BUILD_NUMBER}" || echo "No changes to commit"
                                git push https://$GIT_TOKEN@github.com/Thanh8804/hospital-booking-manifests.git HEAD:main
                            '''
                        }
                    }
                }
            }
        }
        stage('Trigger ArgoCD Sync PROD') {
            when{
                changeset "**/frontend/**"
            }
            steps {
                container('node') {
                    withCredentials([string(credentialsId: 'argocd-token', variable: 'ARGOCD_TOKEN')]) {
                        catchError(buildResult: 'UNSTABLE', stageResult: 'FAILURE') {
                            retry(3) {
                                sh '''
                                    argocd app sync $ARGOCD_PROD_APP --timeout 300 
                                '''
                            }
                        }
                     }
                 }
             }
        }
    }
    post {
        always {
            echo "Pipeline '${PIPELINE_NAME}' completed."
        }
        success {
            emailext attachLog: true, 
                     body: "The pipeline '${PIPELINE_NAME} Build #${BUILD_NUMBER}' has completed successfully.", 
                     subject: "Pipeline Success: ${PIPELINE_NAME} - Build #${BUILD_NUMBER}", 
                     to: "${NOTIFY_EMAIL}"
        }
        failure {
            emailext attachLog: true, 
                     body: "The pipeline '${PIPELINE_NAME}' has failed. Please review the attached logs.", 
                     subject: "Pipeline Failed: ${PIPELINE_NAME} - Build #${BUILD_NUMBER}", 
                     to: "${NOTIFY_EMAIL}"
        }
    }
}
