apiVersion: v1
kind: Pod
spec:
  containers:
  - name: node
    image: node:14-alpine
    command: ["sleep"]
    args: ["infinity"]
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command: ["sleep"]
    args: ["9999999"]
    volumeMounts:
    - name: docker-config
      mountPath: /kaniko/.docker
    resources:
      requests:
        cpu: "600m"
        memory: "1000Mi"
      limits:
        cpu: "1200m"
        memory: "2000Mi"
  - name: trivy
    image: aquasec/trivy:latest
    command: ["sleep"]
    args: ["9999999"]
    resources:
      requests:
        cpu: "200m"
        memory: "400Mi"
      limits:
        cpu: "400m"
        memory: "600Mi"
  volumes:
  - name: docker-config
    projected:
      sources:
      - secret:
          name: docker-credentials
          items:
          - key: .dockerconfigjson
            path: config.json
